### ISSUE TITLE
Unable to build the project due to typescript compilation error

### ISSUE THREAD

**Issue by madtisa** [nodelib/nodelib#109]
### Describe the bug

Unable to build project due to ts compilation error

### Steps to reproduce

1. `git clone https://github.com/nodelib/nodelib.git -b 9bde8b8eab7675e30e020ce87eefb96f61719b22`
2. `cd nodelib`
3. `npm i`
4. `npx lerna bootstrap`
5. `npm run build`

### Expected behavior

Project builds successfully

### Actual behavior

Error ([details](https://github.com/madtisa/nodelib/actions/runs/11362626514/job/31604881014)):
```
Error: node_modules/path-scurry/node_modules/lru-cache/dist/commonjs/index.d.ts(973,5): error TS2416: Property 'entries' in type 'LRUCache<K, V, FC>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '() => Generator<[K, V], void, unknown>' is not assignable to type '() => MapIterator<[K, V]>'.
    Call signature return types 'Generator<[K, V], void, unknown>' and 'MapIterator<[K, V]>' are incompatible.
      The types returned by 'next(...)' are incompatible between these types.
        Type 'IteratorResult<[K, V], void>' is not assignable to type 'IteratorResult<[K, V], undefined>'.
          Type 'IteratorReturnResult<void>' is not assignable to type 'IteratorResult<[K, V], undefined>'.
            Type 'IteratorReturnResult<void>' is not assignable to type 'IteratorReturnResult<undefined>'.
              Type 'void' is not assignable to type 'undefined'.
```

### Possible solution

Updating `rimraf` dependency to 6.0.1 fixes the issue (though it requires node >= 20)

### Environment

* OS Version: win 10 (as well as windows-latest, ubuntu-latest, macos-latest from CI)
* Node.js Version: 16.14.0 (as well as 16.20.2, 18.20.4, 20.17.0)
* @nodelib Version: master (9bde8b8eab7675e30e020ce87eefb96f61719b22)

**Comment by mrmlnc** [comment]
Thanks for the issue. Fixed in the master.
