### ISSUE TITLE
[fs.walk] Explore fs.opendir

### ISSUE THREAD

**Issue by mrmlnc** [nodelib/nodelib#46]
https://github.com/nodejs/node/pull/29349
https://github.com/nodejs/node/issues/29941

**Comment by Fishrock123** [comment]
The perf issue should now be alleviated mostly by default, and if you want to optimize, an option for the number of buffered entries can be specified as of https://github.com/nodejs/node/pull/30114, to be in the next release.

**Comment by mrmlnc** [comment]
The current implementation of opendir is twice as slow (1.8ms vs 0.8ms) for traversing the directory. This is more suitable for traversing large directories, but not for a universal tool.
