### ISSUE TITLE
npm install fails with npm-shrinkwrap.json

### ISSUE THREAD

**Issue by SudharakaP** [nodelib/nodelib#50]
I am trying to migrate to [npm-shrinkwrap.json](https://docs.npmjs.com/files/shrinkwrap.json) from [package-lock.json](https://docs.npmjs.com/files/package-lock.json). After doing the migration it seems that `npm install fails` with the message; 

```shell
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path /opt/hostedtoolcache/node/12.16.1/x64/lib/node_modules/.staging/@nodelib/fs.stat-acca4929
npm ERR! dest /home/runner/work/generator-jhipster/generator-jhipster/node_modules/@nodelib/fs.stat
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, rename '/opt/hostedtoolcache/node/12.16.1/x64/lib/node_modules/.staging/@nodelib/fs.stat-acca4929' -> '/home/runner/work/generator-jhipster/generator-jhipster/node_modules/@nodelib/fs.stat'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-03-14T20_14_27_370Z-debug.log
##[error]Process completed with exit code 254.
```

The complete build could be found at; https://github.com/SudharakaP/generator-jhipster/runs/508208140?check_suite_focus=true

Seems that this issue was noticed in some other packages as well; https://github.com/mapbox/node-pre-gyp/issues/264 but in our case it always seems to come from `nodelib`. 

Any help or ideas will be greately appreciated. :smile: 

Related issue: https://github.com/jhipster/generator-jhipster/issues/10099

**Comment by mrmlnc** [comment]
Sorry I don't have more to offer. Millions of people use these packages and do not experience similar problems.

Most likely, the problem is on the user's side, since the error indicates that the file is not on disk. In our projects, this often happened when operations were highly concurrency, or when the IDE was running (blocking the file).

**Comment by SudharakaP** [comment]
@mrmlnc : Thanks for the information and looking into it.

**Comment by jung-youjin** [comment]
@SudharakaP  Hi, I think I'm facing a similar problem. Did you manage to solve this issue?

**Comment by SudharakaP** [comment]
> @SudharakaP Hi, I think I'm facing a similar problem. Did you manage to solve this issue?

@jung-youjin : No I didn't. In our project we eventually decided to stay with `package-lock.json`.
