### ISSUE TITLE
The dependency @nodelib/fs.scandir has a security flaw as identified by a VeraCode static scan

### ISSUE THREAD

**Issue by iamle0pard** [nodelib/nodelib#51]
If you run a VeraCode static security scan against the @nodelib\fs.scandir folder and files within 'node_modules' you will see that there is a flaw identified.

The following flaws have been identified:

http://cwe.mitre.org/data/definitions/73.html
CWE-73: External Control of File Name or Path

From the scan report, these are the filenames and line numbers identified:

async.js: 42
sync.js: 23

Currently using @nodelib/fs.scandir version: 2.1.3

**Comment by mrmlnc** [comment]
Thanks for the information.

The `fs.scandir` packages is a low-level package like `fs.readdir` method in the `fs` module. Based on this, we do not filter the user experience. Anyone who uses this package can do it themselves, if their program requires it.
