### ISSUE TITLE
[fs.walk] breaking out of the loop takes exceptionally long time when in stream mode

### ISSUE THREAD

**Issue by felixhao28** [nodelib/nodelib#57]
Note: this issue only happens on Windows 7 after I have tested on both Windows 10 and Windows 7 with NodeJS version 13.6.0.

```ts
const stream = fsWalk.walkStream("D:\\path\\to\\dir\\node_modules");
for await (const f of stream) {
    console.log(f.name);
    break;
}
```

This code takes a long time to finish in a very large folder (I used my node_modules folder for testing). I guess fs.scandir has the same problem.

**Comment by ivanjeremic** [comment]
I'm not sure if my problem is the same I basically am not able to break out ever I'm stuck in a loop, I use normal promisifyed `walk` and doing.

```js
const walk = util.promisify(fsWalk.walk);

for await (const f of await walk(resolve("."), {
 if (f.path === "somepath") {
  break;
 }
}
```

Any idea what I'm doing wrong and if I miss something? Thanks.

**Comment by mrmlnc** [comment]
Support for Windows 7 ended on January 14, 2020. Node.js 14+ no longer supports Windows 7. I think my packages will follow the same strategy.

So, we do not support Windows 7.
