### ISSUE TITLE
Latests version of packages contain development files

### ISSUE THREAD

**Issue by MatthiasKunnen** [nodelib/nodelib#65]
The packages contain among other things; `.eslintcache`, `tsconfig.tsbuildinfo`, `tsconfig.json`, and spec files. These files increase package size and might contain personal information.

Examples:
 - `@nodelib/fs.scandir@2.1.4`
 - `@nodelib/fs.stat@2.0.4`
 - `@nodelib/fs.walk@1.2.6`

Instead of using blacklisting with `.npmignore` I recommend whitelisting with [the files property in package.json](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files). That way you can't accidentally publish files.

**Comment by iComputer7** [comment]
I noticed this as well. There are also test files included in the modules that are causing my Typescript builds to fail.

Versions:
* `@nodelib/fs.walk@1.2.6`
* `@nodelib/fs.scandir@2.1.4`
* Nodejs version `v14.15.4`
* NPM version `6.14.10`

I don't have any testing libraries installed as dependencies.
Removing the `src/tests` directory for `fs.walk` seems to solve most of my issues.

**Comment by mrmlnc** [comment]
Fixed with the following versions:

 - @nodelib/fs.macchiato@1.0.4
 - @nodelib/fs.scandir@2.1.5
 - @nodelib/fs.stat@2.0.5
 - @nodelib/fs.walk@1.2.7
