### ISSUE TITLE
npm WARN tarball tarball data for @nodelib/fs.stat@1.1.2 (sha1-VMWpZEYr49TXivYxNjwY1vqRrCY=) seems to be corrupted. Trying one more time.

### ISSUE THREAD

**Issue by u10k** [nodelib/nodelib#80]
npx: installed 1 in 1.55s

  System:
    OS: Windows 10 10.0.19041
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 3.44 GB / 15.87 GB
  Binaries:
    Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\node_modules\yarn\bin\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD

npm i error

**Comment by mrmlnc** [comment]
The problem does not apply to this repository. Most likely it is a network problem, npm problem or problem with npm mirrors.
